#start=stepper_motor.exe#
JMP INICIO

VUELTA_HORARIO  DB  0000_0110B  ;6H - 6
                DB  0000_0100B  ;4H - 4
                DB  0000_0011B  ;3H - 3
                DB  0000_0010B  ;2H - 2
 
INICIO:
    ;MOVEMOS A BX, VUELTA_HORARIO
    MOV BX, OFFSET VUELTA_HORARIO   ;INICIAMOS DESDE LA POSICION
    MOV SI, 0
    MOV CX, 0   ;CONTADOR DE PASOS                    
SIGUIENTE_PASO:
    ;STEPPER MOTOR FUNCIONA EN EL PIN 7
    ;SE REALIZA UNA COMPROBACIÓN DE QUE 
    ;ESTÉ FUNCIONANDO CORRECTAMENTE
    WAIT:
        IN      AL, 07H
        TEST    AL, 10000000B
        JZ  WAIT ;SI EQUIVALE A CERO SEGUIRÁ ESPERANDO
    ;SI YA ESTÁ LISTO ENTONCES COMIENZA
    MOV AL, [BX][SI] 
    OUT 7, AL   ;LE MANDA LA NUEVA POSICIÓN AL MOTOR
    ;INCREMENTA LA POSICIÓN
    INC SI      
    CMP SI, 4   ;COMPARA SI YA DIÓ LOS 4 PASOS
                ;YA QUE ES UN MOTOR DE 4 PASOS
                ;SI YA COMPLETÓ 4 PASOS REGRESA 
                ;A LA POSICIÓN INICIAL
    JC  SIGUIENTE_PASO 
    MOV SI, 0
    JMP SIGUIENTE_PASO   